### ISSUE TITLE
Compilation Issue

### ISSUE THREAD

**Issue by zagannath** [julienr/protobuf-android#1]
HI @julienr Thank you very much for this repository but while compiling im getting bellow errors please suggest me how to fix this

$ ./build.sh 
[arm64-v8a] Compile++      : protobuf <= message_lite.cc
[arm64-v8a] Compile++      : protobuf <= message.cc
[arm64-v8a] Compile++      : protobuf <= reflection_ops.cc
[arm64-v8a] Compile++      : protobuf <= repeated_field.cc
[arm64-v8a] Compile++      : protobuf <= text_format.cc
In file included from /Users/Pankajbafna/Downloads/protobuf-android-master/example/../..//protobuf-android/src/google/protobuf/stubs/once.h:81:0,
                 from /Users/Pankajbafna/Downloads/protobuf-android-master/example/../..//protobuf-android/src/google/protobuf/generated_message_util.h:44,
                 from /Users/Pankajbafna/Downloads/protobuf-android-master/example/../..//protobuf-android/src/google/protobuf/descriptor.pb.h:22,
                 from /Users/Pankajbafna/Downloads/protobuf-android-master/example/../..//protobuf-android/src/google/protobuf/reflection_ops.cc:40:
/Users/Pankajbafna/Downloads/protobuf-android-master/example/../..//protobuf-android/src/google/protobuf/stubs/atomicops.h:193:65: fatal error: google/protobuf/stubs/atomicops_internals_arm64_gcc.h: No such file or directory
 #include <google/protobuf/stubs/atomicops_internals_arm64_gcc.h>
                                                                 ^
compilation terminated.
In file included from /Users/Pankajbafna/Downloads/protobuf-android-master/example/../..//protobuf-android/src/google/protobuf/stubs/once.h:81:0,
                 from /Users/Pankajbafna/Downloads/protobuf-android-master/example/../..//protobuf-android/src/google/protobuf/generated_message_util.h:44,
                 from /Users/Pankajbafna/Downloads/protobuf-android-master/example/../..//protobuf-android/src/google/protobuf/repeated_field.h:58,
                 from /Users/Pankajbafna/Downloads/protobuf-android-master/example/../..//protobuf-android/src/google/protobuf/repeated_field.cc:37:
/Users/Pankajbafna/Downloads/protobuf-android-master/example/../..//protobuf-android/src/google/protobuf/stubs/atomicops.h:193:65: fatal error: google/protobuf/stubs/atomicops_internals_arm64_gcc.h: No such file or directory
 #include <google/protobuf/stubs/atomicops_internals_arm64_gcc.h>
                                                                 ^
compilation terminated.
make: **\* [obj/local/arm64-v8a/objs/protobuf/src/google/protobuf/reflection_ops.o] Error 1
make: **\* Waiting for unfinished jobs....
make: **\* [obj/local/arm64-v8a/objs/protobuf/src/google/protobuf/repeated_field.o] Error 1
In file included from /Users/Pankajbafna/Downloads/protobuf-android-master/example/../..//protobuf-android/src/google/protobuf/stubs/once.h:81:0,
                 from /Users/Pankajbafna/Downloads/protobuf-android-master/example/../..//protobuf-android/src/google/protobuf/message.cc:42:
/Users/Pankajbafna/Downloads/protobuf-android-master/example/../..//protobuf-android/src/google/protobuf/stubs/atomicops.h:193:65: fatal error: google/protobuf/stubs/atomicops_internals_arm64_gcc.h: No such file or directory
 #include <google/protobuf/stubs/atomicops_internals_arm64_gcc.h>
                                                                 ^
compilation terminated.
make: **\* [obj/local/arm64-v8a/objs/protobuf/src/google/protobuf/message.o] Error 1
In file included from /Users/Pankajbafna/Downloads/protobuf-android-master/example/../..//protobuf-android/src/google/protobuf/stubs/once.h:81:0,
                 from /Users/Pankajbafna/Downloads/protobuf-android-master/example/../..//protobuf-android/src/google/protobuf/generated_message_util.h:44,
                 from /Users/Pankajbafna/Downloads/protobuf-android-master/example/../..//protobuf-android/src/google/protobuf/descriptor.pb.h:22,
                 from /Users/Pankajbafna/Downloads/protobuf-android-master/example/../..//protobuf-android/src/google/protobuf/text_format.cc:51:
/Users/Pankajbafna/Downloads/protobuf-android-master/example/../..//protobuf-android/src/google/protobuf/stubs/atomicops.h:193:65: fatal error: google/protobuf/stubs/atomicops_internals_arm64_gcc.h: No such file or directory
 #include <google/protobuf/stubs/atomicops_internals_arm64_gcc.h>
                                                                 ^
compilation terminated.
make: **\* [obj/local/arm64-v8a/objs/protobuf/src/google/protobuf/text_format.o] Error 1

**Comment by julienr** [comment]
Hi, thanks for the report. Indeed, there was a missing header file for ARM64. This is fixed in master.

**Comment by zagannath** [comment]
Thank you very much @julienr
